### ISSUE TITLE
Feature:  Option for filetypes to ignore

### ISSUE THREAD

**Issue by rawhat** [ecthelionvi/NeoColumn.nvim#1]
I didn't see anything listed in the options, but for some stuff like file trees, lazy/packer, etc. it would be nice to have this plugin not apply the column. (roughly) Similar plugins do have this functionality, so there is some precedent. Thanks!

**Comment by ecthelionvi** [comment]
Originally I did have a mechanism to disable certain file types, but since the colorcolumn is off by default and must be toggled on to show the colorcolumn it shouldn't show the colorcolumn in those files unless you enable it. If that is not the case please let me know. I can certainly add an excluded_ft option the config.

**Comment by rawhat** [comment]
Ah I see! If I wanted to make an `autocmd` to run it for every file, do you expect there would be a performance penalty? That would be my preferred way to set it up, so I don't have to think about toggling it. In that case, I could probably just specify the filetype in there. If that makes sense, I can just close this. Appreciate your time :)

**Comment by ecthelionvi** [comment]
Not it's ok, please leave this up. I will work on making a config option to turn it on by default on every file, except the excluded_ft. I will by default exclude buffers that are not modifiable and bufnames ~= "", which should cover most cases in which you do not want a colorcolumn, such as terminals or lazy for example.

**Comment by ecthelionvi** [comment]
I went ahead and implemented the requested changes. But I could use your help testing the update. If you do not mind please change your  plugin config to pull from the `dev` branch. I added an `always_on` variable, by default it is set to `false`. I have also added an `excluded_ft = {}` variable which is a list of filetypes strings on which NeoColumn is excluded. If `always_on` is enabled the bufs list that the plugin uses then becomes the disabled bufs list so you can still toggle the colorcolumn off/on if you desire. If the filetype is in the`excluded_ft` list, the toggle is disabled. By default NeoColumn will not be active on `terminal` buffers and buffers with `nofile` buftypes. Please let me know if these changes are working satisfactory.

**Comment by rawhat** [comment]
Looks great to me, thank you!
