### ISSUE TITLE
Setup doesn't work as expected?

### ISSUE THREAD

**Issue by akijakya** [ecthelionvi/NeoColumn.nvim#5]
Hi, first of all thanks for the great plugin!

One thing I noticed, I was only able to make my custom setting to go through if I set the value of `vim.g.neocolumn_setup` to `false` before calling the setup function, like this:

```lua
local status, neocolumn = pcall(require, "NeoColumn")
if not status then
	return
end

vim.g.neocolumn_setup = false

neocolumn.setup({
	fg_color = colorscheme.base01,
	bg_color = colorscheme.base09,
	NeoColumn = { "80", "120" },
})
```

Is this the intended behavior?

**Comment by ecthelionvi** [comment]
My apologies. The way I was handling the setup was incorrect. You should be able to simply call setup now, I have removed the global variable.

**Comment by akijakya** [comment]
Nice, thanks! 🙂
