### ISSUE TITLE
a string cannot be given to custom_NeoColumn as seen in README.md

### ISSUE THREAD

**Issue by zDonik1** [ecthelionvi/NeoColumn.nvim#6]
Hey, I was checking the plugin and have an issue when I set a string in custom_NeoColumn:

```lua
custom_NeoColumn = {
  go = "100",
}
```

The README.md states that a string can be given:

![image](https://github.com/ecthelionvi/NeoColumn.nvim/assets/25223592/c641fddc-111f-481c-9451-dc2fb5187492)

but there is no string handling in NeoColumn.lua:

```lua
      if config.custom_NeoColumn[filetype] then
        for _, v in ipairs(config.custom_NeoColumn[filetype]) do
          fn.matchadd("ColorColumn", "\\%" .. v .. "v.", 100)
        end
      else
        for _, v in ipairs(NeoColumn_value) do
          fn.matchadd("ColorColumn", "\\%" .. v .. "v.", 100)
        end
      end
```

ipairs expects a table and not a string.

Thanks

**Comment by ecthelionvi** [comment]
Thanks for bringing this to my attention. I just pushed an update that should fix the issue. Please let me know if that works as expected.
